// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujtuuvwcfosbafowsmog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdHV1dndjZm9zYmFmb3dzbW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTE0MzQsImV4cCI6MjA3MzI4NzQzNH0.X5zO3dgWVEIx4IiiuMlUQHPhWeNFF67IiLOn2mnlQq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});